### PR TITLE
Sentiment analysis

### PR DESCRIPTION
**Pull request by glautervl**
First version of Sentiment Analysis Service

### CODE REVIEW

**Comment by vforvalerio87** [comment]
Approved.

**Comment by ferrouswheel** [comment]
Some feedback:

- This PR adds a bunch of IDE config to our repo but also adds things to the .gitignore. I have my own PyCharm config and this will clash with it.
- The IDE config files also mean that most commits have unrelated IDE changes... which makes it noisy to try to review the code.
- This PR adds a bunch of corpus/data files to the repo. Is git the best place to store our training data?
- The PR includes compiled protobuf files are added to the repo, ideally these generated files wouldn't be checked into git and would be generated from a script.

**Comment by andre-senna** [comment]
Typically it makes sense to keep model files in the repo but not training data. 

However, in this specific case the repo is not just the source of a service to be provided but also a tutorial to ease the life of whoever is trying to write/integrate new services in SNET. So I think the repo should be self-contained. One of the designed services is exactly training of a new model based in a passed corpus, so having a corpus to be used as example (in the case the person have none) is very useful.

**Comment by glautervl** [comment]
For the IDE settings, for sure, it should not be there... I marked it as excluded from commits,  added to gitignore, I'll check it out.

About the protobuf compiled files, we can compile the protobuf models on the first action of the run_service.py and keep it independent of a deployment process.

**Comment by glautervl** [comment]
Sure, we must put it in the deployment script on our platform, but thinking about the "external user" experience that just have cloned our repo and start using the service locally, it should not work to him at the first moment...  well.. I can put some instructions on readme file about before running the service.

**Comment by ferrouswheel** [comment]
Okay, if the corpus data is used to demonstrate the use of the service then it kind of makes sense to keep it. It's already part of our repo history now so there is nothing to be gained from removing it unless we force push a rewritten git history.

However redistributing data does raise questions about the license. We should probably at least provide a README.md that points to the provenance of the dataset (is it from [here](http://ai.stanford.edu/~amaas/data/sentiment/)?)

I think we have to be careful of what we are talking about with "models". There are trained machine learning models, but there is also the protobuf data model. I've raised this point of confusion in our `#platform-support` slack, so hopefully we can come up with more distinct terminology for the grpc stuff.

If we're talking about grpc, I would just have a script that builds the models... `singnet/face-services` has [build_proto.sh](https://github.com/singnet/face-services/blob/master/build_proto.sh) as well as a bat file for windows. It shouldn't be tied to the deployment process at all, because a developer may want to regenerate the grpc models while working on the service.

**Comment by pennachin** [comment]
On the overloading of model: https://github.com/singnet/snet-cli/issues/36

**Pull request merged**
